# Python for Data Analysis
##### Reproduced by Albert Marin

_Chapters 1_ to _3_ in this book are just for reviewing general stuff about the python environment. Therefore, we can skip all of those and jump into action :)!

Firstly, we should import all the libraries that are going to be needed in this notebook. Note that we are going to configure the plots to be in line with the code as well as the style of the plots.

In [1]:
from bs4 import BeautifulSoup as BS
import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import sqlite3
import sys

#Inline plots:
%matplotlib inline

#Beautiful R-like plots:
plt.style.use('ggplot')

## Chapter 4: NumPy review
Now let's make a fast review of the numpy arrays with a dummy example.

In [2]:
data = np.random.random(size = (2,3))

#Properties and display:
print('A random matrix: \n{}\n'.format(data))
print('Shape of the matrix (rows, columns): {}\nDimension of the matrix: {}\n'.format(data.shape, data.ndim))
print('Change the type of matrix: \n{}\n'.format(data.astype(np.complex64)))

#Operations:
print('Operations {}'.format(80*'*'))
print('1. Addition: \n{}\n'.format(data+data))
print('2. Multiplication by scalar: \n{}\n'.format(data*10))
print('3. Multiplication bite-wise: \n{}\n'.format(data*data))
print('4. Multiplication (AxB): \n{}\n'.format(np.dot(data,data.T)))

#Slicing:
print('Slicing {}'.format(83*'*'))
print('1. First row: {}\n'.format(data[0]))
print('2. First element of second row: {}\n'.format(data[1][0]))
print('3. Last two elements of first row: {}\n'.format(data[0][-2:]))
print('4. Elements in the whole matrix that are over 0.5: {}\n'.format(data[data>0.5]))
print('5. Elements of the first row that are over 0.5: {}\n'.format(data[0,data[0]>0.5]))
print('6. Elements of the first row that are over 0.5 and less than 0.7: {}\n'.format(
        data[0][(data[0] > 0.5) & (data[0] < 0.7)]))
mask = (data[0] > 0.5) & (data[0] < 0.7)
print('7. The same, with a mask: {}\n'.format(data[0][mask]))

#Renaming values:
print('Others {}'.format(84*'*'))
data[:,0] = -9
print('1. Now the first column is -9: \n{}\n'.format(data))
data[data<0.6] = 0
print('2. Now everything less than 0.6 is 0: \n{}\n'.format(data))

A random matrix: 
[[ 0.28356098  0.76727679  0.72284837]
 [ 0.66196884  0.21997557  0.77913749]]

Shape of the matrix (rows, columns): (2, 3)
Dimension of the matrix: 2

Change the type of matrix: 
[[ 0.28356099+0.j  0.76727676+0.j  0.72284836+0.j]
 [ 0.66196883+0.j  0.21997556+0.j  0.77913749+0.j]]

Operations ********************************************************************************
1. Addition: 
[[ 0.56712196  1.53455359  1.44569674]
 [ 1.32393769  0.43995113  1.55827498]]

2. Multiplication by scalar: 
[[ 2.83560982  7.67276793  7.22848369]
 [ 6.61968844  2.19975566  7.7913749 ]]

3. Multiplication bite-wise: 
[[ 0.08040683  0.58871368  0.52250976]
 [ 0.43820275  0.04838925  0.60705523]]

4. Multiplication (AxB): 
[[ 1.19163027  0.91968895]
 [ 0.91968895  1.09364723]]

Slicing ***********************************************************************************
1. First row: [ 0.28356098  0.76727679  0.72284837]

2. First element of second row: 0.6619688435236506

3. Last two e

Other very useful functions to create ndarrays are: **`arange`, `ones`, `zeros`, `empty`, `eye`**.
For element-wise operations, they are the same as one could expect: `max`, `abs`, `sqrt`, etc.

A finding function that deserves its own place iw the `np.where()` because it's super fast. It's usually used to make new arrays based on a condition.  Suppose you had a matrix of data and you wanted to replace all positive values with 2 and all negative values with -2 or only the positive values.

In [3]:
data2 = np.random.rand(4,4)*np.random.choice([-2.5,2.5],(4,4))
print('Original matrix: \n{}\n'.format(data2))
data3 = np.where(data2 > 0, 2, -2)
print('Replace both positive and negative values: \n{}\n'.format(data3))
data4 = np.where(data2 > 0, 2, data2)
print('Replace only positive values: \n{}'.format(data4))
#Delete all the variables
del data, mask, data2, data3, data4

Original matrix: 
[[-2.45117979  0.00854989  0.6879897   0.89944026]
 [-0.61285632  1.20429941 -1.55071196 -0.13599763]
 [-0.247793    2.0573997   1.04829997 -1.49928059]
 [-1.29392961 -1.38517953 -1.05323869  1.92243222]]

Replace both positive and negative values: 
[[-2  2  2  2]
 [-2  2 -2 -2]
 [-2  2  2 -2]
 [-2 -2 -2  2]]

Replace only positive values: 
[[-2.45117979  2.          2.          2.        ]
 [-0.61285632  2.         -1.55071196 -0.13599763]
 [-0.247793    2.          2.         -1.49928059]
 [-1.29392961 -1.38517953 -1.05323869  2.        ]]


## Chapter 5: basic `pandas` in action
Pandas has a structure that has to be learn, as every module or package. In order to do so, let's create dummy data structures and work with them to exemplify the cases to handle the pandas structure.

### 5.1 pd.Series( )

In [4]:
#  BASIC CRETAION OF SERIES:
data = pd.Series([2,3,-9,7])

#Information of the series:
print('Data:\n{}\n'.format(data))
print('Values: {}\n'.format(data.values))
print('Indexes: {}\n'.format(data.index))

#Redefine the series with names for the indexes:
data.index = ['a','b','c','d']
print('Renamed indexes (I):\n{}\n'.format(data))
data = pd.Series([2,3,-9,7], index = ['a','b','c','d'])
print('Renamed indexes (II):\n{}\n'.format(data))
data.name = 'Dummy thing :)'
data.index.name = 'Alphabet'
print('Renamed attributes:\n{}\n'.format(data))

#Delete the names we created because it's annoying for the examples:
data.name, data.index.name = None, None

Data:
0    2
1    3
2   -9
3    7
dtype: int64

Values: [ 2  3 -9  7]

Indexes: RangeIndex(start=0, stop=4, step=1)

Renamed indexes (I):
a    2
b    3
c   -9
d    7
dtype: int64

Renamed indexes (II):
a    2
b    3
c   -9
d    7
dtype: int64

Renamed attributes:
Alphabet
a    2
b    3
c   -9
d    7
Name: Dummy thing :), dtype: int64



In [5]:
#  ACCESSING DATA AND CHANGING IT:
print(data, end = '\n\n')
print('1. Access the data with key "a": {}\n'.format(data['a']))
print('2. Access the data with keys "d", "b", "c" in this particular order:\n{}\n'.format(data[['d', 'b', 'c']]))

data['a'] = 0
print('3. Access the edited data with key "a": {}\n'.format(data['a']))
print('4. Check data that is greather than 0:\n{}\n'.format(data[data > 0]))
print('5. Multiply data by 5:\n{}\n'.format(data*5))
print('6. Check existence of "c" in data: {}'.format('c' in data))

a    2
b    3
c   -9
d    7
dtype: int64

1. Access the data with key "a": 2

2. Access the data with keys "d", "b", "c" in this particular order:
d    7
b    3
c   -9
dtype: int64

3. Access the edited data with key "a": 0

4. Check data that is greather than 0:
b    3
d    7
dtype: int64

5. Multiply data by 5:
a     0
b    15
c   -45
d    35
dtype: int64

6. Check existence of "c" in data: True


Panda objects can be built from lists, numpy arrays (as seen) or dictionaries. When using a dictionary, the keys will be used as indexes sorted by alphabetical order. Also, an interesting thing is that when we are selecting a subset of the panda's object, if the value doesn't exist, it will store it as a `nan` value as shown below: the vowels different from `a` are not defined in the series so they will be undefined.

In [6]:
data2 = data[['a', 'e', 'b', 'i', 'c', 'o', 'd', 'u']]
print('{}\n'.format(data2))
print('We can check if the data is missing:\n{}'.format(data2[['a', 'e', 'i', 'o', 'u']].isnull()))

a    0.0
e    NaN
b    3.0
i    NaN
c   -9.0
o    NaN
d    7.0
u    NaN
dtype: float64

We can check if the data is missing:
a    False
e     True
i     True
o     True
u     True
dtype: bool


Then, if we are trying to add something that doesn't exist in two different series, the result will be `nan` for the values that are present in only one series.

### 5.2 pd.DataFrame( )

In [7]:
#  BASIC CRETAION OF SERIES:
data = {'City': ['Barcelona', 'Barcelona', 'Barcelona', 'Lleida', 'Lleida'],
        'Year': [2015, 2016, 2017, 2016, 2017],
        'Pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)

#It is automatically sorted, but we can change it:
print('Sorted by default:\n{}\n'.format(frame))
print('Sorted as we want:\n{}\n'.format(pd.DataFrame(data, columns=['Year', 'City', 'Pop'])))

frame_letters = pd.DataFrame(frame.values, index=list('edcba'), columns=list('cba'))
print('Original:\n{}\nSort by index:\n{}\nSort by columns:\n{}\nSort by population:\n{}\n'.format(
    frame_letters, frame_letters.sort_index(),
    frame_letters.sort_index(axis = 1), frame.sort_values(by = 'Pop')))
# <!> Adding the "ascending" parameter, we can sort it in inverse order <!>

frame2 = pd.DataFrame(data, columns=['Year', 'City', 'Pop', 'PIB'], index = list('abcde'))
print('Missing data works like in pd.Series:\n{}\n'.format(frame2))

#Describe the numerical values:
print(frame2.describe())

Sorted by default:
        City  Pop  Year
0  Barcelona  1.5  2015
1  Barcelona  1.7  2016
2  Barcelona  3.6  2017
3     Lleida  2.4  2016
4     Lleida  2.9  2017

Sorted as we want:
   Year       City  Pop
0  2015  Barcelona  1.5
1  2016  Barcelona  1.7
2  2017  Barcelona  3.6
3  2016     Lleida  2.4
4  2017     Lleida  2.9

Original:
           c    b     a
e  Barcelona  1.5  2015
d  Barcelona  1.7  2016
c  Barcelona  3.6  2017
b     Lleida  2.4  2016
a     Lleida  2.9  2017
Sort by index:
           c    b     a
a     Lleida  2.9  2017
b     Lleida  2.4  2016
c  Barcelona  3.6  2017
d  Barcelona  1.7  2016
e  Barcelona  1.5  2015
Sort by columns:
      a    b          c
e  2015  1.5  Barcelona
d  2016  1.7  Barcelona
c  2017  3.6  Barcelona
b  2016  2.4     Lleida
a  2017  2.9     Lleida
Sort by population:
        City  Pop  Year
0  Barcelona  1.5  2015
1  Barcelona  1.7  2016
3     Lleida  2.4  2016
4     Lleida  2.9  2017
2  Barcelona  3.6  2017

Missing data works like in pd.Ser

Other functions similar to `describe()` that can be used are basic statistics such as `min()`, `var()`, `kurt()`, etc. Also, if we want to obtain a fancy output, it can be achieved by just calling the dataframe:

In [8]:
frame2

Year       City  Pop  PIB
a  2015  Barcelona  1.5  NaN
b  2016  Barcelona  1.7  NaN
c  2017  Barcelona  3.6  NaN
d  2016     Lleida  2.4  NaN
e  2017     Lleida  2.9  NaN

Accessing data in a dataframe has different points:
 * A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute.
 * A row can also be retrieved by position or name by a couple of methods, such as the iloc indexing field.

In [9]:
#Columns:
print('See which ones we have: {}\n'.format(frame2.columns))
print('Check the cities:\n{}\n'.format(frame2.City))
print('Check the population:\n{}\n'.format(frame2['Pop']))

#Rows:
print('Check the row "b" by using its name:\n{}\n'.format(frame2.loc['b']))
print('Check the row "b" by using its index in the indexes list:\n{}\n'.format(frame2.iloc[1]))

#Access a value:
print('Check the year from the row "b": {}\n'.format(frame2.iloc[1].Year))

#Boolean indexing:
print('Check the values for the years later than 2015:\n{}'.format(frame2[frame2.Year > 2015]))

See which ones we have: Index(['Year', 'City', 'Pop', 'PIB'], dtype='object')

Check the cities:
a    Barcelona
b    Barcelona
c    Barcelona
d       Lleida
e       Lleida
Name: City, dtype: object

Check the population:
a    1.5
b    1.7
c    3.6
d    2.4
e    2.9
Name: Pop, dtype: float64

Check the row "b" by using its name:
Year         2016
City    Barcelona
Pop           1.7
PIB           NaN
Name: b, dtype: object

Check the row "b" by using its index in the indexes list:
Year         2016
City    Barcelona
Pop           1.7
PIB           NaN
Name: b, dtype: object

Check the year from the row "b": 2016

Check the values for the years later than 2015:
   Year       City  Pop  PIB
b  2016  Barcelona  1.7  NaN
c  2017  Barcelona  3.6  NaN
d  2016     Lleida  2.4  NaN
e  2017     Lleida  2.9  NaN


If we want to modify a value, we can do it exactly the same as the Series. The only difference here is that if we want to change the whole column, we only need to specify one single value for the whole column. If we assign less values than it needs, they will be full of `nan`. Consider the following:

In [10]:
frame2.PIB = 0.9
print(frame2, end = '\n\n')

PIBs = pd.Series([0.95, 2, 1.2], index=['b', 'c', 'e'])
frame2.PIB = PIBs
print(frame2)

   Year       City  Pop  PIB
a  2015  Barcelona  1.5  0.9
b  2016  Barcelona  1.7  0.9
c  2017  Barcelona  3.6  0.9
d  2016     Lleida  2.4  0.9
e  2017     Lleida  2.9  0.9

   Year       City  Pop   PIB
a  2015  Barcelona  1.5   NaN
b  2016  Barcelona  1.7  0.95
c  2017  Barcelona  3.6  2.00
d  2016     Lleida  2.4   NaN
e  2017     Lleida  2.9  1.20


A very interesting function to use is the `unique()` method for the dataFrame as it will return the set of values that are unique.

In [11]:
#The * is used to unwrap the list.
#The sorted reverse = True is used to reverse the order of the output.

print(*sorted(frame2.City.unique().tolist(), reverse=True))

print('\nCount how many Barcelonas and Lleidas we have:\n{}\n'.format(frame2.City.value_counts()))

#If we wanted to count the data in a matrix, we can use the `apply()` mapping function:
example = pd.DataFrame({'Qu1': np.random.randint(1, high=6, size = 5), 
                  'Qu2': np.random.randint(1, high=6, size = 5),
                  'Qu3': np.random.randint(1, high=6, size = 5)})
print('Original:\n{}\nCounted values:\n{}'.format(example, example.apply(pd.value_counts).fillna(0)))

Lleida Barcelona

Count how many Barcelonas and Lleidas we have:
Barcelona    3
Lleida       2
Name: City, dtype: int64

Original:
   Qu1  Qu2  Qu3
0    5    1    1
1    2    4    1
2    3    1    3
3    5    5    5
4    4    4    1
Counted values:
   Qu1  Qu2  Qu3
1  0.0  2.0  3.0
2  1.0  0.0  0.0
3  1.0  0.0  1.0
4  1.0  2.0  0.0
5  2.0  1.0  1.0


An important feature is the `reindex()` function with the filling options of `fill_value=`, `ffill` and `bfill`.

In [12]:
frame2 = pd.DataFrame(frame, columns = ['Year', 'City', 'Pop'])

print('Fills with NaN:\n{}\n'.format(frame2.reindex(np.arange(6))))
print('Fills with specic value:\n{}\n'.format(frame2.reindex(np.arange(6), fill_value=0)))
print('Make column and row:\n{}'.format(frame2.reindex([0,1,2,3,4,5], method='ffill').reindex(
                                                    columns=['Year', 'City', 'Pop', 'Record'])))

Fills with NaN:
     Year       City  Pop
0  2015.0  Barcelona  1.5
1  2016.0  Barcelona  1.7
2  2017.0  Barcelona  3.6
3  2016.0     Lleida  2.4
4  2017.0     Lleida  2.9
5     NaN        NaN  NaN

Fills with specic value:
   Year       City  Pop
0  2015  Barcelona  1.5
1  2016  Barcelona  1.7
2  2017  Barcelona  3.6
3  2016     Lleida  2.4
4  2017     Lleida  2.9
5     0          0  0.0

Make column and row:
   Year       City  Pop  Record
0  2015  Barcelona  1.5     NaN
1  2016  Barcelona  1.7     NaN
2  2017  Barcelona  3.6     NaN
3  2016     Lleida  2.4     NaN
4  2017     Lleida  2.9     NaN
5  2017     Lleida  2.9     NaN


An interesting operation is when we have to sum things and there are `nan` values. In these cases, we can use the option to skip or not those values:

In [13]:
df = pd.DataFrame([[1, np.nan], [5, -2], [np.nan, np.nan], [3, -1]],
                   index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
print('Df:\n{}\n'.format(df))
print('Sum everything even it has nans:\n{}\n'.format(df.sum(axis=1)))
print('Sum if the row does not have nans:\n{}'.format(df.sum(axis=1, skipna = False)))

Df:
   one  two
a  1.0  NaN
b  5.0 -2.0
c  NaN  NaN
d  3.0 -1.0

Sum everything even it has nans:
a    1.0
b    3.0
c    NaN
d    2.0
dtype: float64

Sum if the row does not have nans:
a    NaN
b    3.0
c    NaN
d    2.0
dtype: float64


### 5.3 Handling missing data
As it can appear everywhere, it is interesting to have a few aces up the sleeve just in case we need to use them. The easiest thing to do is to check whether they are missing values with the method `.isnull()`. `NaN` and `None` will both be treated as missing values. After this, we can use a few strategies:
 * `.dropna()` method: it will simply eliminate the missing values and return a clearn dataframe. We can pass some parameters on `how` which are `all` (the rows with a full `NaN` value) or `axis=`.
 * `.fillna()` method: already seen. We can fill it with a value, an array, `ffill` or `bfill`.

In [14]:
#Clean by dropping:
missing = pd.DataFrame([[4.2, 1.5, 2.4, 2., 1.8],
                        [1., 6.5, 3., 2, np.nan],
                        [1., np.nan, np.nan, np.nan, np.nan], 
                        [np.nan, np.nan, np.nan, np.nan, np.nan], 
                        [np.nan, 6.5, 3., np.nan, np.nan]])

print('Original:\n{}\n'.format(missing))
print('Clean I drop rows with NaN:\n{}\n'.format(missing.dropna()))
print('Clean II empty lines (either direction):\n{}\n'.format(missing.dropna(how = 'all')))
print('Clean III drop rows with NaN:\n{}\n'.format(missing.dropna(axis = 0)))
print('Clean IV drop empty rows:\n{}\n'.format(missing.dropna(axis = 0, how = 'all')))
print('Clean V drop columns with NaN :\n{}\n'.format(missing.dropna(axis = 1)))
print('Clean VI empty columns:\n{}\n'.format(missing.dropna(axis = 1, how = 'all')))
print('Clean VII thresholded rows:\n{}\n'.format(missing.dropna(thresh = 3)))
print('Clean VIII thresholded columns:\n{}'.format(missing.dropna(thresh = 3, axis = 1)))

Original:
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8
1  1.0  6.5  3.0  2.0  NaN
2  1.0  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  6.5  3.0  NaN  NaN

Clean I drop rows with NaN:
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8

Clean II empty lines (either direction):
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8
1  1.0  6.5  3.0  2.0  NaN
2  1.0  NaN  NaN  NaN  NaN
4  NaN  6.5  3.0  NaN  NaN

Clean III drop rows with NaN:
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8

Clean IV drop empty rows:
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8
1  1.0  6.5  3.0  2.0  NaN
2  1.0  NaN  NaN  NaN  NaN
4  NaN  6.5  3.0  NaN  NaN

Clean V drop columns with NaN :
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

Clean VI empty columns:
     0    1    2    3    4
0  4.2  1.5  2.4  2.0  1.8
1  1.0  6.5  3.0  2.0  NaN
2  1.0  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  6.5  3.0  NaN  NaN

Clean VII thresholded rows:
     0    1    2    3

### 5.4 Advanced indexing: hierarchical indexing or multiindexing
This advanced method is used to have 2 or more index levels. It is useful to work with higher dimensional data in a lower dimensional data format.

In [15]:
#Simple example of multiindexed series:
data = pd.Series(np.random.randn(10), index = [list('aaabbbccdd'),[1,2,3,1,2,3,1,2,2,3]])
print(data, end='\n\n')
print(data.index)

a  1   -0.987740
   2    2.316092
   3   -1.784533
b  1    0.627223
   2    0.458714
   3    0.249351
c  1   -0.328768
   2   -0.479698
d  2    0.603799
   3    1.834328
dtype: float64

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])


To access the data, is the same as in the normal indexing but adding another level. A way to re-order this is by the command `.unstack()`.

In [16]:
data.unstack()

1         2         3
a -0.987740  2.316092 -1.784533
b  0.627223  0.458714  0.249351
c -0.328768 -0.479698       NaN
d       NaN  0.603799  1.834328

Note that either axis can have the multiindexing:

In [17]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),index=[['One', 'One', 'Two', 'Two'], [1, 2, 1, 2]],
                  columns=[['Barcelona', 'Barcelona', 'Lleida'], ['Orange', 'Red', 'Orange']])
frame.index.names = ['N', 'n']
frame.columns.names = ['City', 'Col']
print(frame)
print(frame['Barcelona', 'Orange']['One'])

City  Barcelona     Lleida
Col      Orange Red Orange
N   n                     
One 1         0   1      2
    2         3   4      5
Two 1         6   7      8
    2         9  10     11
n
1    0
2    3
Name: (Barcelona, Orange), dtype: int64


## Chapter 6: data loading, storage and file formats
Usually, we won't generate random data like we were generating in the previous chapter. We will have to load `.txt` files, or `.sql` databases and _then_ work with them. This chapter focuses in this. Remember that:
 * Statements started by `!` are meant to be executed as in the terminal.
 * Statements started by `%` are _magic_ commands.
 
### 6.1 `read_csv( )` and `read_table( )`

In [18]:
#Lets peak into the csv example:
!cat PythonForDataAnalysis/ex1.csv

#Method 1:
df = pd.read_csv('PythonForDataAnalysis/ex1.csv')
#Method 2:
df2 = pd.read_table('PythonForDataAnalysis/ex1.csv', sep=',')

df if all(df == df2) else 'Methods are not equivalent'

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
#Data without headers:
df = pd.read_csv('PythonForDataAnalysis/ex2.csv', header=None)
print('Original headerless:\n{}\n'.format(df))
print('Artificially created:\n{}\n'.format(pd.read_csv('PythonForDataAnalysis/ex2.csv',
                                                     names=['a','b','c','d','message'])))
print('Using "message" column as indexes:\n{}'.format(pd.read_csv('PythonForDataAnalysis/ex2.csv',
                                                     names=['a','b','c','d','message'],
                                                     index_col = 'message')))

Original headerless:
   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

Artificially created:
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Using "message" column as indexes:
         a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12


In [20]:
#Data with multiindex:
!cat PythonForDataAnalysis/ex3.csv
parsed = pd.read_csv('PythonForDataAnalysis/ex3.csv', index_col = ['key1','key2'])
parsed

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16


value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

If the data has a more problematic storage, we will need to use regular expressions (more info: [tutorial 1](https://docs.python.org/2/library/re.html), [tutorial 2](http://www.regular-expressions.info/)). For example, let's suppose that a file has whitespaces as delimiter but in some cases there are many of them and sometimes it's just one. We can solve it by using the `\s+` regular expression.

In [21]:
!cat PythonForDataAnalysis/ex4.csv
result = pd.read_csv('PythonForDataAnalysis/ex4.csv', sep = '\s+')
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb 0.927272 0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382 1.100491



A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

The pattern can be more intricate than this. We can have `nan` values, that we can manage by specifying `na_values=` that will replace the `nan` values by whatever we tell it to do. The list of things availables are:

In [22]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=False, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, skip_footer=0, doublequote=True, delim_whitespace=False, as_recarray=False, compact_ints=False, use_unsigned=False, low_memory=True, buffer_lines=None, memory_map=False, float_precision=No

Finally, it is worth mentioning that we can store the results in a CSV file easily. We can do it by importing the CSV package and specify a lot of things or do it straightaway:

In [23]:
result.to_csv('PythonForDataAnalysis/out1.csv', sep='|')
!cat PythonForDataAnalysis/out1.csv

|A|B|C
aaa|-0.264438|-1.026059|-0.6195
bbb|0.927272|0.302904|-0.032399000000000004
ccc|-0.264273|-0.386314|-0.21760100000000002
ddd|-0.871858|-0.348382|1.1004909999999999


### 6.2 Read JSON
JSON (short for JavaScript Object Notation) has become one of the standard formats for sending data by HTTP request between web browsers and other applications. It is a much more flexible data format than a tabular text form like CSV.

In [24]:
#JSON object example:
obj = """{"name": "Wes",
          "places_lived": ["United States", "Spain", "Germany"],
          "pet": null,
          "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
                       {"name": "Katie", "age": 33, "pet": "Cisco"}]
         }"""

In [25]:
#Check if we have imported the json module! Just to be sure.
if 'json' not in sys.modules.keys(): import json
    
#Convert it to python dictionary
result = json.loads(obj)
print(result)

#Convert it back to JSON format:
asjson = json.dumps(result)

#Obtain a DataFrame (as an example) out of the siblings variable
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

{'pet': None, 'name': 'Wes', 'siblings': [{'age': 25, 'pet': 'Zuko', 'name': 'Scott'}, {'age': 33, 'pet': 'Cisco', 'name': 'Katie'}], 'places_lived': ['United States', 'Spain', 'Germany']}


name  age
0  Scott   25
1  Katie   33

Data from the JSON can be stored as conviniently as we want it to be.

### 6.3 Read XML/HTML
The basic idea is that we need to use the `request` package, which is one of the easiest to use, and then use `BeautifulSoup`, to access the HTML/XML format in a easy way. When we have retreived the data, we will need to work a bit to obtain the information that we want and then we can pass it to a panda's structure. We will work an example of _Yahoo! Finances_ database.

In [26]:
#Check if we have imported the requests module! Just to be sure.
if 'requests' not in sys.modules.keys(): import requests
if 'bs4' not in sys.modules.keys(): from bs4 import BeautifulSoup as BS

#Obtain the raw data:
rawweb = requests.get('https://finance.yahoo.com/quote/AAPL/options?ltr=1')
print(rawweb)

<Response [200]>


The `requests.get( )` returns a _response [code]_ which is an object that contains all the information of the webpage. The code tells us if it could read it (code 200) or if something happened. In order to work with it, we could transform it into a json format but unfortunately this webpage can't be transformed into that format. For cases like that, the best idea is to use a parser such as bs4 (`BeautifulSoup`) and work with it.

In [27]:
#Transform it into a BeautifulSoup object which is a easy manipulable parser
web_parsed = BS(rawweb.text, 'html.parser')

#Let's check the title:
print(*web_parsed.title)

#Let's find all the links in the page:
links = web_parsed.find_all('a')
print(*['{}\n'.format(i['href']) for i in links[:10]])

#...or the tables with the interesting data:
tables = web_parsed.find_all('table')
print(*['{}\n'.format(i.get_text()[:144]) 
        if len(i.get_text()) < 144 
        else '{}... (there is more!)'.format(i.get_text()[:144]) 
        for i in tables[:2]])

AAPL Option Chain | Apple Inc. Stock - Yahoo Finance
https://www.yahoo.com/
 https://mail.yahoo.com/?.intl=us&.lang=en-US
 https://www.flickr.com/
 https://www.tumblr.com/
 https://www.yahoo.com/news/
 http://sports.yahoo.com/
 http://finance.yahoo.com/
 https://www.yahoo.com/celebrity/
 https://answers.yahoo.com/
 https://groups.yahoo.com/

Search
 Contract NameLast Trade DateStrikeLast PriceBidAskChange% ChangeVolumeOpen InterestImplied VolatilityAAPL170825C000950002017-08-16 11:52AM EDT95... (there is more!)


From the tables, we can see that the one with information is table 1. Now that we have obtained the information from the URL, let's try to improve it.

In [28]:
f = tables[1]

#Now with a bit of intelligence, we can obtain the table :)
#   1. Get the column names:
columns = [i.get_text().capitalize() for i in f.find_all('th')]

#   2. The contract names are treated as links. Need for special synthax:
ContractNames = [i.get_text() for x, i in enumerate(f.find_all('a')) if x%2==0]

#   3. Start building the dictionary with the contract names:
data = {columns[0]: ContractNames}

#   4. Get the rest of the values:
for i in range(1, len(columns)):
    col = 'data-col{}'.format(i)
    cellcontent = [i.get_text() for i in f.find_all('td', attrs={'class':col})]
    data[columns[i]] = cellcontent

#   5. Create the pandas structure in the same order as the webpage!
finance = pd.DataFrame(data=data, columns=columns)

#   6. Fix the issue of using "-" instead of NaN for missing values:
finance['% change'].replace(to_replace = '-', value = np.nan, inplace = True)
finance.head()

Contract name         Last trade date  Strike Last price    Bid  \
0  AAPL170825C00095000  2017-08-16 11:52AM EDT   95.00      67.02  62.10   
1  AAPL170825C00100000  2017-08-14 12:03PM EDT  100.00      59.15  57.10   
2  AAPL170825C00110000   2017-08-14 2:05PM EDT  110.00      50.05  47.10   
3  AAPL170825C00115000   2017-08-16 9:30AM EDT  115.00      46.87  42.10   
4  AAPL170825C00120000  2017-08-18 12:59PM EDT  120.00      39.20  37.15   

     Ask Change % change Volume Open interest Implied volatility  
0  63.00   0.00      NaN      1             1            146.09%  
1  58.00   0.00      NaN      1             1            132.81%  
2  48.00   0.00      NaN      5             6            107.03%  
3  43.00   0.00      NaN      1             1             94.92%  
4  38.00  -1.63   -3.99%      6             0             87.89%

### 6.5 Database formats (mySQL,...)
It is very common that data is stored in a database structure such as the SQL and non-SQL formats, which stand for Search Query Language. Reading the data into python is very straightforward. We can use the `sqlite3` package from the Python standard library to connect to the sqlite database and create a cursor. A `sqlite3.Cursor` object is our interface to the database, mostly throught the execute method that allows to run any SQL query on our database.

First of all we can get a list of all the tables saved into the database, this is done by reading the column name from the sqlite_master metadata table with:

    SELECT name FROM sqlite_master

If we want everything, we just need to use the wildcard `*` instead of the `name` in the query.
The output of the execute method is an iterator that can be used in a for loop to print the value of each row or a shortcut to directly execute the query and gather the results is the `.fetchall()` method:

In [29]:
if 'sqlite3' not in sys.modules.keys(): import sqlite3

#Create the cursor:
conn = sqlite3.connect('../DDBB/iris.sqlite')
cursor = conn.cursor()

#Get the names of the tables:
name1 = []
for row in cursor.execute("SELECT name FROM sqlite_master"):
    name1.append(row)
name2 = cursor.execute("SELECT name FROM sqlite_master").fetchall()

#Read the name of the database:
print(*name1[0])

#Instruction to read the database:
irisdata = pd.read_sql_query("SELECT * FROM {}".format(*name1[0]), conn)

#Display it:
irisdata.set_index('Id', inplace=True)
irisdata.head()

Iris


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

A more advanced query would have been:
    
    SELECT * FROM Iris WHERE Species == 'Iris-setosa'
   
in which we are saying _select everything from the database "Iris" which have "iris-setosa" as a tag for species_. More details on how to make SQL queries can be found in the [webpage](https://docs.python.org/3/library/sqlite3.html) or in some [tutorials](http://zetcode.com/db/sqlitepythontutorial/). `sqlite3` is extremely useful for downselecting data **before** importing them in `pandas`.

For example you might have 1 TB of data in a table stored in a database on a server machine. You are interested in working on a subset of the data based on some criterion, unfortunately it would be impossible to first load data into `pandas` and then filter them, therefore we should tell the database to perform the filtering and just load into `pandas` the downsized dataset.

## Chapter 7: data wrangling - clean, transform, merge and reshape
Data contained in pandas objects can be combined together in a number of built-in ways:
* `pandas.merge()` connects rows in DataFrames based on one or more keys. It implements database join operations, as in relational databases.
* `pandas.concat()` glues or stacks together objects along an axis.
* `combine_first()` instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

### 7.1 `merge( )` and `join( )`
This pandas operation will perform a join between two tables based on the key table that we define. Then the basic usage is `pd.merge([table1], [table2], on = [column], how = [style])`. The types of junction are the following:
![Join types](joins.jpg)

In [30]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})

print('1. Inner:\n{}\n'.format(pd.merge(df1, df2, on='key')))
print('2. Left:\n{}\n'.format(pd.merge(df1, df2, on='key', how = 'left')))
print('3. Right:\n{}\n'.format(pd.merge(df1, df2, on='key', how = 'right')))
print('4. Outer:\n{}\n'.format(pd.merge(df1, df2, on='key', how = 'outer')))

1. Inner:
   data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

2. Left:
   data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      3   c    NaN
4      4   a    0.0
5      5   a    0.0
6      6   b    1.0

3. Right:
   data1 key  data2
0    0.0   b      1
1    1.0   b      1
2    6.0   b      1
3    2.0   a      0
4    4.0   a      0
5    5.0   a      0
6    NaN   d      2

4. Outer:
   data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0



If the key to merge is in the index, we can merge it by passing a parameter for it.

In [31]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
right1 = pd.DataFrame({'group_val':[3.5,7]}, index = list('ab'))
print(pd.merge(left1, right1, left_on = 'key', right_index = True))

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0


If each table has multiple keys, we can do the following:

In [32]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                   'key2': ['one', 'two', 'one'],
                   'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
print('{}\n{}\n'.format(left,right))
print('Merged multiple keys: \n{}\n'.format(pd.merge(left, right, on=['key1', 'key2'], how='outer')))

#Add suffixes if we have the same key but different values:
print('Suffixes: \n{}\n'.format(pd.merge(left, right, on='key1', suffixes=('_LEFT', '_RIGHT'))))

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

Merged multiple keys: 
  key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

Suffixes: 
  key1 key2_LEFT  lval key2_RIGHT  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7



In order to merge through indexes, we can use join (for simple cases) or if we hierarchical data, one has to indicate that the indexes are what we are looking for:

In [33]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                  index=['a', 'c', 'e'],
                  columns=['Barcelona', 'Lleida'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]], 
                   index=['b', 'c', 'd', 'e'], 
                   columns=['Girona', 'Tarragona'])
print('Simple join:\n{}\n'.format(left2.join(right2, how = 'outer')))

left3 = pd.DataFrame({'key1':['Barcelona','Barcelona','Barcelona','Lleida','Lleida'],
                      'key2':[2015,2016,2017,2016,2017],
                      'data': np.arange(5)})
right3 = pd.DataFrame(np.arange(12).reshape((6,2)),
                     index = [['Barcelona','Barcelona','Lleida','Lleida','Lleida','Lleida'],
                             [2016, 2015, 2015, 2015, 2016, 2017]],
                     columns = ['one', 'two'])
print('Hierarchical join:\n{}'.format(pd.merge(left3, right3, left_on=['key1','key2'], right_index=True)))

Simple join:
   Barcelona  Lleida  Girona  Tarragona
a        1.0     2.0     NaN        NaN
b        NaN     NaN     7.0        8.0
c        3.0     4.0     9.0       10.0
d        NaN     NaN    11.0       12.0
e        5.0     6.0    13.0       14.0

Hierarchical join:
   data       key1  key2  one  two
0     0  Barcelona  2015    2    3
1     1  Barcelona  2016    0    1
3     3     Lleida  2016    8    9
4     4     Lleida  2017   10   11


### 7.2 `concat( )`
As described above, it is used to stack the data.

In [34]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
print('Stack the data as rows:\n{}\n'.format(pd.concat([s1, s2, s3])))
print('Stack the data as columns (creates DataFrame):\n{}\n'.format(pd.concat([s1, s2, s3], axis = 1)))

#We can pass the "how" parameter here too but it's called "join":
s4 = pd.concat([s1 * 5, s3])
print('Outer join:\n{}\n'.format(pd.concat([s1, s4], axis=1)))
print('Inner join:\n{}'.format(pd.concat([s1, s4], axis=1, join='inner')))

Stack the data as rows:
a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

Stack the data as columns (creates DataFrame):
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

Outer join:
     0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

Inner join:
   0  1
a  0  0
b  1  5


When concatenating the data, we might want to keep an origin reference of the indexes, which we can achieve by passing the parameter `keys = []` or maybe we don't need to keep the indexes, which we can achieve by `ignore_index = True`.

In [35]:
print('Set the axis keys:\n{}\n'.format(pd.concat([s1, s4], axis=1, keys=['S1', 'S4'])))
print('Forget the indexes:\n{}'.format(pd.concat([s1, s4], axis=0, ignore_index=True)))

Set the axis keys:
    S1  S4
a  0.0   0
b  1.0   5
f  NaN   5
g  NaN   6

Forget the indexes:
0    0
1    1
2    0
3    5
4    5
5    6
dtype: int64


### 7.3 `combine_first( )`
You may have two datasets whose indexes overlap in full or part. As a motivating example, consider `np.where()` function, which expressed a vectorized if-else. It works with three parameters:
 * Condition to check.
 * Value if true.
 * Value if false.

In [36]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan

print('Original series\n#A#\n{}\n#B#\n{}\n'.format(a,b))

#Find the NaN values in a, then if they are, use the value in b. Otherwise keep the value in a:
print('Resulted vector:\n{}\n'.format(np.where(pd.isnull(a),b,a)))
print('Same with pandas but outputs a Series:\n{}\n'.format(a.combine_first(b)))

#In DataFrames it works similarly column by column:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                 'b': [np.nan, 2., np.nan, 6.],
                 'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                 'b': [np.nan, 3., 4., 6., 8.]})
print('DF combine first:\n{}'.format(df1.combine_first(df2)))

Original series
#A#
f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
#B#
f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

Resulted vector:
[ 0.   2.5  2.   3.5  4.5  nan]

Same with pandas but outputs a Series:
f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

DF combine first:
     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN


### 7.4 Pivoting
Sometimes we need to re-organize the data in a easy way and perhaps get it stacked. We can do it with `pivot()`

In [37]:
#Read the data:
data = pd.read_csv('../Pythoneo/PythonForDataAnalysis/ex5.csv')
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')
data = pd.DataFrame(data.to_records(),
                 columns=pd.Index(['realgdp', 'infl', 'unemp'], name='item'),
                 index=periods.to_timestamp('D', 'end'))

#Results:
ldata = data.stack().reset_index().rename(columns={0: 'value'})
print('Raw data:\n{}\n'.format(ldata.head(10)))
wdata = ldata.pivot('date', 'item', 'value')
print('Pivoted data:\n{}\n'.format(wdata.head(10)))
ldata['value2'] = np.random.randn(len(ldata))
wdata2 = ldata.pivot('date', 'item')
print('If we ignore the last parameter, we can have more keys:\n{}'.format(wdata2.head(10)))

Raw data:
        date     item     value
0 1959-03-31  realgdp  2710.349
1 1959-03-31     infl     0.000
2 1959-03-31    unemp     5.800
3 1959-06-30  realgdp  2778.801
4 1959-06-30     infl     2.340
5 1959-06-30    unemp     5.100
6 1959-09-30  realgdp  2775.488
7 1959-09-30     infl     2.740
8 1959-09-30    unemp     5.300
9 1959-12-31  realgdp  2785.204

Pivoted data:
item        infl   realgdp  unemp
date                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
1959-09-30  2.74  2775.488    5.3
1959-12-31  0.27  2785.204    5.6
1960-03-31  2.31  2847.699    5.2
1960-06-30  0.14  2834.390    5.2
1960-09-30  2.70  2839.022    5.6
1960-12-31  1.21  2802.616    6.3
1961-03-31 -0.40  2819.264    6.8
1961-06-30  1.47  2872.005    7.0

If we ignore the last parameter, we can have more keys:
           value                    value2                    
item        infl   realgdp unemp      infl   realgdp     unemp
date                            

### 7.5 Data transformation
We can do a set of things:

In [38]:
#Remove duplicates:
print('{}Remove duplicates'.upper().format('\t'*6))
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
print('1. Oritinal data:\n{}\n'.format(data))
print('2. No duplicates:\n{}\n'.format(data.drop_duplicates()))

data['v1'] = range(7)
print('3. Drop duplicates of a column:\n{}\n'.format(data.drop_duplicates(['k1'])))
print('4. Keep the last duplicated value instead of the first:\n{}\n'.format(
    data.drop_duplicates(['k1', 'k2'], keep='last')))

#Map a function:
print('{}Function mapping'.upper().format('\t'*6))
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef', 'Bacon', 'pastrami', 'honey ham',
                           'nova lox'],
                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
meat_to_animal = {'bacon': 'pig',
                  'pulled pork': 'pig',
                  'pastrami': 'cow',
                  'corned beef': 'cow',
                  'honey ham': 'pig',
                  'nova lox': 'salmon'}

print('1. Manual mapping:\n{}\n'.format(data['food'].map(str.lower).map(meat_to_animal)))
print('2. Lambda mapping:\n{}\n'.format(data['food'].map(lambda x: meat_to_animal[x.lower()])))

#Replacing values and index re-naming:
print('{}Replacing values and index re-naming'.upper().format('\t'*5))
print('Already seen in cells "In [4]:" & "In [5]:"\n\n')

#Data binning:
print('{}Data binning'.upper().format('\t'*6))
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats2 = pd.cut(ages,bins,right=False)
cats3 = pd.cut(ages,bins,labels=['Young', 'YoungAdult', 'MiddleAged', 'Senior'])
data = np.random.randn(1000)
cats4 = pd.qcut(data,4)
cats5 = pd.qcut(data,[0, 0.1, 0.5, 0.9, 1])
print('1. Category codes:{}\n'.format(cats.codes))
print('2. Category categories:\n{}\n'.format(cats.categories))
print('3. Category categories with right bound open:\n{}\n'.format(cats2.categories))
print('4. Counting the categories:\n{}\n'.format(pd.value_counts(cats)))
print('5. Naming the category:\n{}\n'.format(cats3.categories))
print('6. Cutting by standard quantiles:\n{}\n'.format(pd.value_counts(cats4)))
print('7. Cutting by custom quantiles:\n{}\n'.format(pd.value_counts(cats5)))

#Replacing values and index re-naming:
print('{}Detecting outliers'.upper().format('\t'*6))
print('Already seen in cells "In [4]:" & "In [5]:" (boolean indexing)\n\n')

#Easy random subsampling:
print('{}Random subsampling'.upper().format('\t'*6))
df = pd.DataFrame(np.arange(20).reshape(5,4))
sampler = np.random.permutation(5)
print('1. Original data:\n{}\n'.format(df))
print('2. Random subsample of 2 rows:\n{}\n'.format(df.take(sampler)[:2]))

#Value matrix: to find the places where our data has values:
print('{}Value matrix'.upper().format('\t'*6))
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})
print('1. Original data:\n{}\n'.format(df))
print('2. Matrix value:\n{}\n'.format(pd.get_dummies(df['key'])))
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
print('3. Summary dataframe:\n{}\n'.format(df_with_dummy))

#Real life example:
    #Load and obtain genres
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('../Pythoneo/PythonForDataAnalysis/movielens.dat', sep='::', header=None,
                        names=mnames)
genre_iter = [set(x.split('|')) for x in movies.genres]
genres = sorted(set.union(*genre_iter))
    #Preallocate matrix for speed and fill it with ones if the genre appears
dummies = pd.DataFrame(np.zeros((len(movies), len(genres))), columns = genres)
for i,gen in enumerate(movies.genres):
    dummies.loc[i, gen.split('|')] = 1
movies_windic = movies.join(dummies.add_prefix('Genre_'))
print(movies_windic.loc[0])

						REMOVE DUPLICATES
1. Oritinal data:
    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

2. No duplicates:
    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

3. Drop duplicates of a column:
    k1  k2  v1
0  one   1   0
3  two   3   3

4. Keep the last duplicated value instead of the first:
    k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

						FUNCTION MAPPING
1. Manual mapping:
0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

2. Lambda mapping:
0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

					REPLACING VALUES AND INDEX RE-NAMING
Already seen in cells "In [4]:" & "In [5]:"


						DATA BINNING
1. Category codes:[0 0 0 1 0 0 2 1 3 2 2 1]

2. Category categories:
IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='

/home/al/.local/lib/python3.5/site-packages/ipykernel_launcher.py:76: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

## Chapter 9: Data aggregation and group operations
Chapter 8 is only about drawing with matplotlib, so it is skipped. This section is fully dedicated to the `groupby( )` method. It is useful because it allows us to:
 1. Split a pandas object into pieces using one or more keys (in the form of functions, arrays, or DataFrame column names).
 2. Computing group summary statistics, like count, mean, or standard deviation, or a user-defined function.
 3. Apply a varying set of functions to each column of a DataFrame.
 4. Apply within-group transformations or other manipulations, like normalization, linear regression, rank, or subset selection.
 5. Compute pivot tables and cross-tabulations.
 6. Perform quantile analysis and other data-derived group analyses

The basic mechanism is to split the data - apply operation - combine the result. The output of a `groupby` method will always be an object. It hasn't computed anything yet and we have to request what we want from it as in the example below:

In [39]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
print('1. DataFrame:\n{}\n'.format(df))

#Group data 1 column by the key 1:
grouped = df['data1'].groupby(df['key1'])
grouped2 = df['data1'].groupby([df['key1'], df['key2']])
print('2. Group object: {}\n'.format(grouped))

#Operation:
print('3. Absolutes by group:\n{}\n'.format(grouped.apply(abs)))
print('4. Sum by group:\n{}\n'.format(grouped.sum()))
print('5. Means by group:\n{}\n'.format(grouped.mean()))
print('6. Means by groupS:\n{}\n\n'.format(grouped2.mean()))

#Group all data by the key 1:
grouped3 = df.groupby('key1')
grouped4 = df.groupby([df['key1'], df['key2']])

#Operation:
print('7. Sum by group:\n{}\n'.format(grouped3.sum()))
print('8. Means by group:\n{}\n'.format(grouped3.mean()))
print('9. Means by groupS:\n{}\n'.format(grouped4.mean()))

#See the groups:
print('10. See the groups:\n{}\n{}\n{}\n{}'.format(grouped.groups, 
                                                   grouped2.groups, 
                                                   grouped3.groups, 
                                                   grouped4.groups))

1. DataFrame:
      data1     data2 key1 key2
0  0.247948 -0.027877    a  one
1  1.961050  0.518072    a  two
2 -2.167729 -0.823758    b  one
3  0.643310 -0.664134    b  two
4  0.034184  0.081383    a  one

2. Group object: <pandas.core.groupby.SeriesGroupBy object at 0x7f0948c653c8>

3. Absolutes by group:
0    0.247948
1    1.961050
2    2.167729
3    0.643310
4    0.034184
Name: data1, dtype: float64

4. Sum by group:
key1
a    2.243182
b   -1.524420
Name: data1, dtype: float64

5. Means by group:
key1
a    0.747727
b   -0.762210
Name: data1, dtype: float64

6. Means by groupS:
key1  key2
a     one     0.141066
      two     1.961050
b     one    -2.167729
      two     0.643310
Name: data1, dtype: float64


7. Sum by group:
         data1     data2
key1                    
a     2.243182  0.571578
b    -1.524420 -1.487892

8. Means by group:
         data1     data2
key1                    
a     0.747727  0.190526
b    -0.762210 -0.743946

9. Means by groupS:
              data1  

And this is it! All the most interesting and basic features to work with the `pandas` package are the ones that have been presented in this notebook.  Happy coding!